"""Build reduced-motion copies of the profile's animated SVG artwork."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSETS = (
    "cats/header-about.svg",
    "cats/header-tech.svg",
    "cats/header-stats.svg",
    "cats/header-3d.svg",
    "cats/header-connect.svg",
    "cats/cat-waving.svg",
    "cats/cat-sleeping.svg",
    "cats/cat-coding.svg",
    "scenes/universe-hero.svg",
    "scenes/night-garden.svg",
)
DISABLE_ANIMATION = '<style>* { animation: none !important; }</style>'


def build_static_copy(relative_path: str) -> None:
    source = ROOT / "assets" / relative_path
    destination = ROOT / "assets" / "static" / Path(relative_path).name
    content = source.read_text(encoding="utf-8")
    if "</svg>" not in content:
        raise ValueError(f"Missing closing SVG element: {source}")
    static_content = content.replace(
        "</svg>",
        f"  <!-- Generated by scripts/build-static-art.py; edit the animated source. -->\n  {DISABLE_ANIMATION}\n</svg>",
        1,
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(static_content.rstrip("\n") + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    for asset in ASSETS:
        build_static_copy(asset)


if __name__ == "__main__":
    main()
